### ISSUE TITLE
Data not logging but file created

### ISSUE THREAD

**Issue by Stephen-Lail** [COAST-Lab/Biogeochemical-Drifter#5]
When the sensors are taking measurements, they are reading out to the terminal and the .csv file is created but nothing is being read onto the SD card. When I open the SD card, it shows a file is created but the file is 0 bytes. I'm not entirely sure where in the code the malfunction is but I am going to look into the printToFile function.

**Comment by SUPScientist** [comment]
Happy to take a look. Here are a few thoughts:
1. Looking at `printToFile()` definitely sounds like the right place to start.
2. In general, helpful to link to the specific file with which you're having trouble (e.g., I assume this https://github.com/COAST-Lab/Biogeochemical-Drifter/blob/main/Firmware/Drifter_Code_V2/src/Drifter_Code_V2.cpp and I assume it's 100% up to date on github, but helpful to be explicit in issues so that I can be certain I'm looking at what you're looking at.
3. I pulled up a similar example from another repo that we know works: https://github.com/COAST-Lab/Open-Water-Level/blob/9bbe509c7290716d0b862424d65e20587a265c41/Firmware/SLR_Boron_Maxbotix_MB7092_cm/src/SLR_Boron_Maxbotix_MB7092_cm.cpp#L150-L166. One difference I note is the absence in your `printToFile()` of a `dataFile.close()` line at the end. I think it needs to be closed to actually save, then reopened next loop.
4. I also see in that same example some differences in the way the file object is called and then used throughout. 

I imagine once you polish up 3 and 4 you'll be in good shape. Post with updates/further questions!
